name: 04 - Uisng Actions
on: 
  push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Print Folders
              run: |
                echo "This job is running"
                echo "runner: $RUNNER_OS"
                echo "Folders in the repository:"
                ls -la
