name: 03 - Workflow Runners
on: push

jobs:
    ubuntu-echo:
        runs-on: ubunt-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running "
                echo "runner: $RUNNER_OS"
                
    window-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                echo "This job is running"
                echo "runner: $RUNNER_OS"
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run : | 
                echo "This job is running"
                echo "runner: $RUNNER_OS"
